Beste <!CC var [voornaam]>,

<p>Alvast bedankt voor je interesse in Projectkoor CHANTage. Bij deze sturen wij je een unieke link naar het auditiemateriaal waarmee je aan de slag kan.
<p>Wanneer je op onderstaande link klikt kom je op een beveiligde pagina waar je het auditiemateriaal kan downloaden. 
<p><b>OPGELET: </b>Omdat we je de kans willen geven eerst het materiaal door te nemen vooraleer je je definitief kandidaat stelt moet je je inschrijving nog definitief bevestigen. Dat kan je door op je auditiepagina te klikken op 'bevestig mijn inschrijving'.
<p><a href="http://www.projectkoorchantage.be/modules/audities/auditiepagina.php?key=<!CC VAR [key]>">Klik hier om naar je auditiepagina te gaan</a>
<p>Succes en hopelijk tot op de auditie van 25 januari!
<p>Els Vanoverschelde, Nele Fiers, Matthias Bauw, Sarah Finaut en Geert De Deygere
<p>Projectkoor CHANTage