<h1>Aanvraag ontvangen</h1>
Bedankt voor je aanvraag! Je ontvangt zo dadelijk een mail met jouw unieke link naar het auditiemateriaal.
<p>Laat je vrienden weten dat je ervoor gaat: <div class="fb-like" data-href="http://www.projectkoor.be" data-send="false" data-width="450" data-show-faces="true" data-font="arial" data-colorscheme="dark"></div>
<p><span id="nadruk">OPGELET!</span>: Je bent nog niet ingeschreven! We raden je aan om het materiaal eerst eens rustig door te nemen. In de E-mail die je ontvangt vind je de instructies om je inschrijving te bevestigen.
<p>Succes!
<p>Els, Nele, Geert, Matthias en Sarah