<h1>Aanvraag ontvangen</h1>
Bedankt voor je aanvraag! Je ontvangt zo dadelijk een mail met jouw unieke link naar het auditiemateriaal.
<p>Laat je vrienden weten dat je ervoor gaat: <div class="fb-share-button" data-href="http://www.projectkoorchantage.be/modules/audities/index.php" data-type="button_count"></div>
<p><span class="nadruk">OPGELET!</span>: Je bent nog niet definitief ingeschreven! We raden je aan om het materiaal eerst eens rustig door te nemen. In de e-mail die je ontvangt vind je de instructies om je inschrijving te bevestigen.
<p>Veel succes!