Beste <!CC var [voornaam]>,

<p>Je bent nu ingeschreven voor de audities voor het projectkoor!
<p>Van zodra de inschrijvingen afgesloten worden maken wij een planning op en krijg je de datum en uur waarop je verwacht wordt. Gelieve voorlopig de auditiedag (25 januari 2014) vrij te houden!
<p>Els Vanoverschelde, Nele Fiers, Matthias Bauw, Sarah Finaut en Geert De Deygere 
<p>Projectkoor CHANTage