Welkom bij de nieuwsbriefdienst van jestaatnietalleen.be!
<P>Via deze nieuwsbrieven houden wij je op de hoogte van onze KMO-acties in uw regio.
<P>Door op onderstaande link te klikken kan je bevestigen op welke van onze nieuwsbrieven je wenst te abonneren.Als je dat wenst kan je deze instelling later nog aanpassen.
<p><center><h1><a href="http://www.jestaatnietalleen.be/modules/nieuwsbrief/presentation/confirm.php?key=<!CC VAR [key]>">Bevestig je aanmelding</a></h1></center>
<BR>Bedankt voor je interesse!
<BR>ACV Brugge-Oostende-Westhoek