<h1><!CC LANG [LANG_ERROR_REPORT]></h1>
<h2>Exception details</h2>
<table>
    <tr><th><!CC LANG [LANG_ERROR_MESSAGE]></th><td><!CC VAR [message]></td></tr>
    <tr><th><!CC LANG [LANG_ERROR_FILE]></th><td><!CC VAR [file]></td></tr>
    <tr><th><!CC LANG [LANG_ERROR_LINE]></th><td><!CC VAR [line]></td></tr>
    <tr><th><!CC LANG [LANG_ERROR_TRACE]></th><td><!CC VAR [trace]></td></tr>
</table>
<h2><!CC LANG [LANG_ERROR_ENV_VARS]></h2>
<h3>POST</h3>
<!CC VAR [post]>
<h3>GET</h3>
<!CC VAR [get]>
