<!DOCTYPE html>
<section class="block">
    <h1>Kerstconcert</h1>
    <p>Projectkoor CHANTage stelt zich aan u voor. We brengen een kerstconcert dat u niet snel zal vergeten. </p>
    <p>Dit concert gaat door in de kerk van Woumen. Het unieke interieur van deze kerk biedt een mix van moderne en authentieke elementen. Dat is meteen ook het concept voor dit eerste concert. We willen ons profileren als een koor dat veel verschillende genres aankan en u een mix van klassieke werken (Mendelssohn, Pachelbel), musicalnummers (Martin Guerre), pop (Sting) tot klassieke kerstnummers (verschillende medleys).</p>
    <p>Het concert wordt gedirigeerd door Geert De Deygere (o.a. muzikaal verantwoordelijke voor de Belgische premiere van 3 Musketiers, de musical in 2011). Het koor wordt begeleid door pianist Jürgen Degryse (leerkracht piano aan de academie van Blankenberge). De helft van de nummers worden volledig a capella gebracht.</p>
</section>
