<link rel="stylesheet" href="/extracss/sponsors.css">
<section class='block'>
    <h1>Sponsors</h1>
<div class='block'>Zonder de steun van deze bedrijven zouden de projecten van Projectkoor CHANTage onmogelijk zijn. We zijn deze bedrijven heel erg dankbaar voor hun steun en hun vertrouwen.</div>
<div class="blocksponsors">
                <a href='http://www.diseno.be/' target='_blank'><img src='/images/sponsors/diseno.png'></a>
                <a href='http://www.diksmuide.be' target='_blank'><img src='/images/sponsors/diksmuide.png'></a>
                <a href='http://koorenstemwestvlaanderen.be/' target='_blank'><img src='/images/sponsors/kswvl.jpg'></a>
                <a href='http://debofisc.be/' target='_blank'><img src='/images/sponsors/advertentie-debofisc-wit.png'></a>
                <a href='http://collegediksmuide.be/' target='_blank'><img src='/images/sponsors/college.png'></a>
                <a href='http://www.automobilia.be/' target='_blank'><img src='/images/sponsors/Automobilia.png'></a>
                <a href='http://www.sym3.be' target='_blank'><img src='/images/sponsors/sym3.png'></a>
                <a href='http://www.qsani.be' target='_blank'><img src='/images/sponsors/qsani.png'></a>
                <a href='http://www.danbredint.be/' target='_blank'><img src='/images/sponsors/danbred.png'></a>
                <a href='http://www.lartduvin.be/nl' target='_blank'><img src='/images/sponsors/lartduvin.png'></a>                
                <a href='http://www.handelsgids.be/diksmuide/de-keyrel-marc-bvba/' target='_blank'><img src='/images/sponsors/dvv.png'></a>                
                <a href='http://www.mariaterengelen.be/' target='_blank'><img src='/images/sponsors/maria-ter-engelen.png'></a>
                <a href='http://www.crelan.be/nl/kantoor-manu-mackelberg' target='_blank'><img src='/images/sponsors/crelan.png'></a>
                <a href='http://www.ishtar.be' target='_blank'><img src='/images/sponsors/ishtar.jpg'></a>
                <a href='#' target='_blank'><img src='/images/sponsors/beenart.png'></a>
                
</div>
<div class="blocksponsors">
    <a href='http://www.kantoorvv.be/nl/index.php' target='_blank'><img src='/images/sponsors/venv.png'></a>
   <a href='http://www.paulvanhulle.be/' target='_blank'><img src='/images/sponsors/vanhulle.png'></a>
    <a href='#' target='_blank'><img src='/images/sponsors/darvan.png'></a>
    
</div>
</section>