CREATE TABLE auditiekandidaten(
id int(4) UNSIGNED ZEROFILL PRIMARY KEY AUTO_INCREMENT,
secretkey varchar(32) NOT NULL,
voornaam VARCHAR(30) NOT NULL,
naam VARCHAR(30) NOT NULL,
mailadres VARCHAR(50) NOT NULL,
stemgroep int(1) NOT NULL,
definitief enum('Y','N') DEFAULT 'N',
adres VARCHAR(100),
gsm VARCHAR(10),
geboortedatum DATE,
hoogstenoot VARCHAR(50),
laagstenoot VARCHAR(50),
partiturenlezen ENUM('Y','N'),
ervaring TEXT,
zangles ENUM('Y','N'),
instrument TEXT,
ervaringinstrument TEXT,
motivatie TEXT
);
